a = input("Digite algo: ")
print("O tipo primitivo desse valor é: ",type(a))
print("Só tem espaços? ", a.isspace())
print("é um número ? ", a.isnumeric)
print("é alfabético ?", a.isalpha())
print("é alfanúmerico ? ", a.isalnum())
print("Está em maiúsculas ? ", a.isupper())
print("Está em minúsculas ? ", a.islower())
print("Está capitalizada ? ", a.istitle())
print("Qual tipo primitivo ?{type(a)}{}".format(type(a),a.isspace()))